### ISSUE TITLE
Parcel's package is parcel-bundler

### ISSUE THREAD

**Issue by rvasilev** [kevincharm/parcel-plugin-web-extension#1]
[Parcel docs](https://parceljs.org/getting_started.html) are saying that `parcel-bundler` is the right name. This plugin is requiring `parcel`

**Comment by kevincharm** [comment]
Good catch, I'll fix it. Looks like other plugins are requiring `parcel-bundler` too. They both seem to be current though:
https://www.npmjs.com/package/parcel
https://www.npmjs.com/package/parcel-bundler

**Comment by kevincharm** [comment]
Fixed with v1.1.0
