### ISSUE TITLE
Windows manifest file paths broken

### ISSUE THREAD

**Issue by NuroDev** [kevincharm/parcel-plugin-web-extension#14]
Any file paths in the `manifest.json` file have the `/` seperator replaced with a `\` and makes it not valid json for a file path.

Source Manifest:
![Source](https://user-images.githubusercontent.com/4991309/44004729-03f45494-9e5f-11e8-9e2b-8049f02f4640.PNG)

Generated Manifest:
![Generated](https://user-images.githubusercontent.com/4991309/44004730-040c82da-9e5f-11e8-8a90-d6c30bfe3492.PNG)

**Comment by mu-yu** [comment]
Any workaround for this issue??

**Comment by jazzzz** [comment]
A workaround is to put all resources referenced by the manifest in the same directory.

I see 3 PRs to address this issue, is there something blocking?

**Comment by kevincharm** [comment]
Sorry for the long, long, long wait. I have merged #35 which should fix this issue.
