### ISSUE TITLE
The "data" argument must be one of type string, TypedArray, or DataView. Received type object

### ISSUE THREAD

**Issue by kolyasya** [kevincharm/parcel-plugin-web-extension#21]
I'm trying to setup dev environment with Parcel and your Package.

I started with a simple structure:

![image](https://user-images.githubusercontent.com/3371143/46250855-696b5300-c44c-11e8-8053-b979df136420.png)

manifest.json 

```
{
  "manifest_version": 2,

  "name": "My Extension",
  "description": "This extension is a starting point to create a real Chrome extension",
  "version": "0.0.1",

  "background": {
    "scripts": [
      "./index.js"
    ],
    "persistent": true
  }

}
```

When I run `parcel build ./manifest.json` I have an error:

![image](https://user-images.githubusercontent.com/3371143/46250842-42148600-c44c-11e8-9287-6f79a10f8b6e.png)

Am I doing something wrong?

**Comment by kevincharm** [comment]
Hi, that error looks unrelated to this package. What version of parcel-bundler/node are you using?

**Comment by kolyasya** [comment]
@kevincharm ooops, sorry. It seems like I was using outdated Parcel version. After upgrading everything works fine, thank you ;-)

**Comment by kevincharm** [comment]
No worries - gonna close this issue.
