### ISSUE TITLE
Building content scripts

### ISSUE THREAD

**Issue by sergey-shpak** [kevincharm/parcel-plugin-web-extension#30]
HI,

First of all parcel + parcel-plugin-web-extension makes my life much :100: easier and happier, thank you!

I'm building 'content scripts' with parcel and the plugin, and then executing those scripts on target pages manually, like: 
```javascript
browser.tabs.executeScript({ file: 'myContentFile.js' })
```
Everything looks quite simple and it works well for Chrome browser, 
but it fails in Firefox with `Error: Script 'moz-extension://.../content.js' result is non-structured-clonable data`, this means that Firefox expects to get clonable data from the content script (but it gets results of `parcelRequire` function export and fails as result)

After some research I found similar issues for browserify,
but is there any workaround or fix for parcel?

**Comment by sergey-shpak** [comment]
As temporary workaround it's possible to wrap content script with [parcel wrapper plugin](https://github.com/albinotonnina/parcel-plugin-wrapper) to return 'structured-clonable data'

Wrapper asset
```javascript
module.exports = ({ name }) => 
  name.split('/').pop() == 'ContentFileName.js'  
    ? { footer: ', 1' } : undefined
```

**Comment by felixfbecker** [comment]
Is there no non-workaround solution?
