### ISSUE TITLE
Parcel v2 support

### ISSUE THREAD

**Issue by fregante** [kevincharm/parcel-plugin-web-extension#52]
This isn't currently picked up by Parcel v2, I hope that the it will be supported soon because it's great with Parcel v1 🎉

**Comment by v1rtl** [comment]
also noticed that, the only thing that bundles is manifest.json but not files

**Comment by mrassili** [comment]
any chance this could be achieved, I'd love to use this plugin with Parcel v2

**Comment by fregante** [comment]
This is now supported natively: https://parceljs.org/recipes/web-extension/

You can look at https://github.com/fregante/github-issue-link-status/pull/39 for an example on how to switch to parcel v1 to v2 with that.

That's all based on template for extensions, which also includes automated publishing https://github.com/fregante/browser-extension-template

**Comment by mrassili** [comment]
> This is now supported natively: https://v2.parceljs.org/recipes/web-extension/
> 
> 
> 
> You can look at https://github.com/fregante/github-issue-link-status/pull/39 for an example on how to switch to parcel v1 to v2 with that.

This is great news 🙌🏼

**Comment by zhyc9de** [comment]
thanks for your news, and i write a [boilerplate](https://github.com/zhyc9de/parcel2-webextension-boilerplate) with parcel2.
